on:
  push:
	branches: [main]
    
jobs:
  deploy:
	name: Deploy to Ec2 instance
	runs-on: self-hosted
	steps:
  	- name: TO EC2 instance
    	run: |
      	npm install
      	npm run build
      	sudo cp -R build/ /var/www/html/testreactapp/
