on:
  push:
    branches: [main]
    
jobs:
  deploy:
    name: Deploy to Ec2 instance
    runs-on: self-hosted
    steps:
      - name: TO EC2 instance
        run: |
          sudo npm install
          sudo npm run build
          sudo cp -R build/ /var/www/html/testreactapp/
          sudo nginx -t && sudo systemctl reload nginx
